add note about not being able to test
add note about not being able to test at mybinder.org

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-b8f8765a5ed7> in <module>()
      7 from matplotlib_venn import *
      8 from matplotlib import pyplot as plt
----> 9 v = venn2(subsets = {'10': 1, '01': 1, '11': 1}, set_labels = ('A', 'B'))
     10 v.get_patch_by_id('10').set_alpha(0.5)
     11 v.get_patch_by_id('10').set_color('orange')

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib_venn/_venn2.pyc in venn2(subsets, set_labels, set_colors, alpha, normalize_to, ax)
    226 
    227     if ax is None:
--> 228         ax = gca()
    229     prepare_venn_axes(ax, centers, radii)
    230 

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py in gca(**kwargs)
    926     matplotlib.figure.Figure.gca : The figure's gca method.
    927     """
--> 928     return gcf().gca(**kwargs)
    929 
    930 # More ways of creating axes:

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py in gcf()
    576         return figManager.canvas.figure
    577     else:
--> 578         return figure()
    579 
    580 

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, **kwargs)
    525                                         frameon=frameon,
    526                                         FigureClass=FigureClass,
--> 527                                         **kwargs)
    528 
    529         if figLabel:

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py in new_figure_manager(num, *args, **kwargs)
     44     FigureClass = kwargs.pop('FigureClass', Figure)
     45     thisFig = FigureClass(*args, **kwargs)
---> 46     return new_figure_manager_given_figure(num, thisFig)
     47 
     48 

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py in new_figure_manager_given_figure(num, figure)
     51     Create a new figure manager instance for the given figure.
     52     """
---> 53     canvas = FigureCanvasQTAgg(figure)
     54     return FigureManagerQT(canvas, num)
     55 

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py in __init__(self, figure)
     74         if DEBUG:
     75             print('FigureCanvasQtAgg: ', figure)
---> 76         FigureCanvasQT.__init__(self, figure)
     77         FigureCanvasQTAggBase.__init__(self, figure)
     78         FigureCanvasAgg.__init__(self, figure)

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py in __init__(self, figure)
     66         if DEBUG:
     67             print('FigureCanvasQt qt4: ', figure)
---> 68         _create_qApp()
     69 
     70         # Note different super-calling style to backend_qt5

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py in _create_qApp()
    136                 display = os.environ.get('DISPLAY')
    137                 if display is None or not re.search(':\d', display):
--> 138                     raise RuntimeError('Invalid DISPLAY variable')
    139 
    140             qApp = QtWidgets.QApplication([str(" ")])

RuntimeError: Invalid DISPLAY variable